CREATE TABLE IF NOT EXISTS 附表3库存调整表 (
调库编号 INTEGER PRIMARY KEY AUTOINCREMENT,
调库时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
库存位置 TEXT NOT NULL,
库存类别 TEXT NOT NULL,
库存名称 TEXT NOT NULL,
库存变化 TEXT NOT NULL
);