CREATE TABLE IF NOT EXISTS 出库表 (
出库编号 INTEGER PRIMARY KEY AUTOINCREMENT,
出库时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
出库位置 TEXT NOT NULL,
出库类别 TEXT NOT NULL,
出库名称 TEXT NOT NULL,
出库数量 INTEGER NOT NULL
);