CREATE TABLE IF NOT EXISTS 入库表 (
入库编号 INTEGER PRIMARY KEY AUTOINCREMENT,
入库时间 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
入库位置 TEXT NOT NULL,
入库类别 TEXT NOT NULL,
入库名称 TEXT NOT NULL,
入库数量 INTEGER NOT NULL
);